### ISSUE TITLE
Simple way to implement prefix (prepend) or sufix (appened) in titles

### ISSUE THREAD

**Issue by iBasit** [sonata-project/SonataSeoBundle#157]
I know how to add it from controller, but I was wondering if there is easy way adding it via configuration, rather then controller. 

``` yaml
sonata_seo:
    page:
        title: "%%translationKey%% - Company Name"
```

so translation key can be replaced by any added title.
