### ISSUE TITLE
Enhancement: autogenerate robots.txt

### ISSUE THREAD

**Issue by Nightbr** [sonata-project/SonataSeoBundle#190]
Hey,
I have look at the code of SonataSeoBundle and I have not found any helper to generate the robots.txt.

Is it a planned feature or not ?

I handle it with a simple twig template so far:

```
# www.robotstxt.org/
# www.google.com/support/webmasters/bin/answer.py?hl=en&answer=156449

User-agent: *
Disallow: /admin
Disallow: /sonatadmin
Disallow: /api
Sitemap: {{ url('sitemap_xml', {'_format':'xml'}) }}

```

But I think it could be a great feature. If it is planned to this bundle and nobody is on it, I can develop it and create a PR.

Anyone interested in this feature ?

**Comment by greg0ire** [comment]
I'm not aware of any plans for this bundle besides maintaining it, but any features are welcome.

**Comment by Nightbr** [comment]
Ok, I implement it in my current project and I will make a PR for the robots.txt features.

keep in touch on this ;)

**Comment by greg0ire** [comment]
Great!

**Comment by Nightbr** [comment]
Hey, here is my thought about robots.txt:

Specification sources: 
* <https://en.wikipedia.org/wiki/Robots_exclusion_standard>
* <http://www.robotstxt.org/norobots-rfc.txt>

First, you can configure the robots.txt into the config.yml:

``` YAML
sonata_seo:
    robotstxt:
        -
            user-agent: [*]
            crawl-delay: 10
            disallow: /admin
            disallow: /sonatadmin
            allow: /api/doc
            disallow: /api
            sitemap: [https://www.example.com/sitemap_index.xml]
            host: www.example.com
        -
            user-agent: [BadRobot, GoogleBot]
            disallow: /private
```

For example, this configuration will generate this robots.txt:

``` TXT
# www.robotstxt.org/
# www.google.com/support/webmasters/bin/answer.py?hl=en&answer=156449

User-agent: *
Crawl-delay: 10
Disallow: /admin
Disallow: /sonatadmin
Allow: /api/doc
Disallow: /api
Sitemap: https://www.example.com/sitemap_index.xml
Host www.example.com

User-agent: BadRobot
User-agent: GoogleBot
Disallow: /private
```


With this structure, I think we can cover all combination for a robots.txt file.

In the `DependencyInjection/SonataSeoExtension.php`, I will create a `function configureRobotstxt(array $config, ContainerBuilder $container)` in order to export the configuration in php array.

After this, I will create a folder `Robotstxt`, with a php file `RobotstxtManager.php` which will generate a valid robots.txt file from a php array.

Is it correct or should I create an `RobotstxtWriter` into `Sonata/Exporter` and use an ArraySourceIterator ?
